### ISSUE TITLE
add favicon?

### ISSUE THREAD

**Issue by lnussel** [openSUSE/distribution-logos#1]
Following up on https://github.com/cockpit-project/cockpit/pull/14684, how about adding a favicon? Either in git or generating it at build time in the spec file?

**Comment by marusak** [comment]
Any update on this?

**Comment by hellcp** [comment]
Whoops, sorry, I wasn't following this repo, let me add that stuff

**Comment by hellcp** [comment]
Verified icons are installed to `/usr/share/pixmaps/distribution-logos/favicon.ico` and forwarded request to factory https://build.opensuse.org/request/show/849085
