### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by gryffus** [openSUSE/distribution-logos#11]
I would like to propose unifying Tumbleweed and Leap logos under this one

![opensuse-logo](https://github.com/user-attachments/assets/1f819cde-ef25-4c9c-8f66-8e07bfb701b4)

Disclaimer: I am not author of this logo, but author allowed its use for the openSUSE project already, so that's a + I guess.

I can provide another variations and formats without a problem.

No, this is not a joke nor trolling.

**Comment by Idesmi** [comment]
There is an ongoing discussion on a bigger rebranding; pertaining to this logo, we might need to get away from using "SUSE" in the name of the project.

**Comment by hellcp** [comment]
No

**Comment by gryffus** [comment]
> No

Nice example of community-driven decision process...
I guess your "explanation" (who you even are? @hellcp ) is the last confirmation I needed.

**Comment by hellcp** [comment]
I'm the maintainer of this repository

**Comment by lkocman** [comment]
I support @hellcp here.
Current direction is to have distribution specific brand "Leap", "Tumbleweed", and kinda skipping the project name which seems to be subject to a change. This would be a step back and would only create more communication mess.

**Comment by gryffus** [comment]
> I support @hellcp here. Current direction is to have distribution specific brand "Leap", "Tumbleweed", and kinda skipping the project name which seems to be subject to a change. This would be a step back and would only create more communication mess.

So to clarify things, issues with this proposal are:

- Not enough of a distinction between Leap and TW
- Inclusion of the project name in the logo

Correct?

**Comment by skriesch** [comment]
Reopen this suggestion! We want to  have it back.
