### ISSUE TITLE
Leap Micro Logo

### ISSUE THREAD

**Issue by hellcp** [openSUSE/distribution-logos#3]
Some noodlings on a logo for Leap Micro logo, compared to the current MicroOS logo
![leap-micro-proto](https://user-images.githubusercontent.com/30577011/155717449-f00b2f17-1675-4c84-a030-894d57160611.png)

**Comment by lkocman** [comment]
I like the most the  logo this one  as it shouts I'm a Leap variation on top of MicroOS
![lkocman-preference](https://user-images.githubusercontent.com/510119/155719785-9acd693e-5255-424d-add8-d1480eac8a17.png)

**Comment by hellcp** [comment]
Perfect, I think the only issue for potential distribution-logos-openSUSE subpackage and get-o-o is finding a fitting colour that would represent the distro
